# libSQL server tuned like OpenStatus's docker-compose.yaml.
FROM ghcr.io/tursodatabase/libsql-server:latest
ENV SQLD_NODE=primary \
    SQLD_MAX_CONCURRENT_CONNECTIONS=512 \
    SQLD_MAX_CONCURRENT_REQUESTS=1024
