import { defineRailway, github, group, image, project, service, volume } from "railway/iac";

// Every service that needs fixed settings is built from a tiny Dockerfile in
// this repo (FROM the upstream image + ENV). Railway's template generator only
// keeps variables that contain ${{...}} references, so anything literal lives
// in those Dockerfiles and the template ends up with just six inputs:
// AUTH_SECRET, CRON_SECRET, OPENSTATUS_KEY (generated by ${{secret(32)}}),
// RESEND_API_KEY (placeholder), dashboard.PORT (3000) and the two Tinybird Local tokens.
const REPO = "ephraimduncan/openstatus-railway";
const fromRepo = (dir: string) => github(REPO, { branch: "main", rootDirectory: dir });

// Secrets of the reference project. In the published template these become ${{secret(32)}}.
const AUTH_SECRET = "eMvhfqafUwDIwAOfOCjhKOwGoKIaqpQPMifhjTUjrkXqALrL";
const CRON_SECRET = "f4c1c8d0d94e7fb74448526350d0f5064eebfe712e145124";
const PROBE_KEY = "42d02842a1c64d39b82bfc762f6ac524";

// Tinybird Local only accepts tokens in the `tb local generate-tokens` format
// (HS256 with a fixed key), so Railway cannot generate them. The service is
// private-network only. See README > "Rotate the Tinybird tokens".
const TINYBIRD_WORKSPACE_TOKEN = "p.eyJ1IjogIjIzZTE0YmFkLWFlYmQtNGVjMi04MTVkLTMyYmI0ZDllNmI0ZCIsICJpZCI6ICJlZjc2NTEwMi0yM2Y1LTQ5OGQtYTMyZS0zMGJkMWRmNzBkNTciLCAiaG9zdCI6IG51bGx9.crYr6k4p1CXjb4bJ3grPMmRDOz4fIoU-fgdJ420bnvo";
const TINYBIRD_USER_TOKEN = "p.eyJ1IjogIjI2OTVhNDEzLTllMTctNDE1YS1hOWFmLTJmMzMxZWMyYzViOCIsICJpZCI6ICIyZDk1YjY1My1hMTA4LTRkZTUtYjc4Mi01ZjE1OTNhZmIwZGUiLCAiaG9zdCI6IG51bGx9.RLsa0HY5A7pP5FnytWFTIwHRIwtacPmKKeaoF6_2L9M";

// Volumes are created in the project's region with the plan default size.
// Mirrored here so `railway config plan` does not propose shrinking them.
const VOLUME = { region: "us-east4-eqdc4a", sizeMB: 50000 };

export default defineRailway(() => {
  // ---------------------------------------------------------------- Data
  const libsql = service("libsql", {
    source: fromRepo("libsql"),
    env: { DATABASE_URL: "http://${{RAILWAY_PRIVATE_DOMAIN}}:8080" },
    volumeMounts: { "/var/lib/sqld": volume("libsql-data", VOLUME) },
    deploy: { restartPolicyType: "ALWAYS" },
  });

  const tinybird = service("tinybird-local", {
    source: fromRepo("tinybird-local"),
    env: {
      TB_LOCAL_WORKSPACE_TOKEN: TINYBIRD_WORKSPACE_TOKEN,
      TB_LOCAL_USER_TOKEN: TINYBIRD_USER_TOKEN,
      TINYBIRD_URL: "http://${{RAILWAY_PRIVATE_DOMAIN}}:7181",
    },
    volumeMounts: { "/data": volume("tinybird-data", VOLUME) },
    deploy: { restartPolicyType: "ALWAYS" },
  });

  // ---------------------------------------------------------------- Jobs (exit 0 when done)
  const dbMigrate = service("db-migrate", {
    source: image("ghcr.io/openstatushq/openstatus-db-migrate:latest"),
    env: { DATABASE_URL: libsql.env.DATABASE_URL },
  });

  const tinybirdDeploy = service("tinybird-deploy", {
    source: fromRepo("tinybird-deploy"),
    env: {
      TB_HOST: tinybird.env.TINYBIRD_URL,
      TB_TOKEN: tinybird.env.TB_LOCAL_WORKSPACE_TOKEN,
    },
    deploy: { restartPolicyMaxRetries: 20 },
  });

  // ---------------------------------------------------------------- Apps
  const workflows = service("workflows", {
    source: fromRepo("workflows"),
    env: {
      PORT: "${{dashboard.PORT}}",
      DATABASE_URL: libsql.env.DATABASE_URL,
      CRON_SECRET: CRON_SECRET,
      WORKFLOWS_URL: "http://${{RAILWAY_PRIVATE_DOMAIN}}:3000",
      SITE_URL: "https://${{dashboard.RAILWAY_PUBLIC_DOMAIN}}",
      RESEND_API_KEY: "${{dashboard.RESEND_API_KEY}}",
      TINY_BIRD_API_KEY: tinybird.env.TB_LOCAL_WORKSPACE_TOKEN,
      TINYBIRD_URL: tinybird.env.TINYBIRD_URL,
    },
    volumeMounts: { "/app/data": volume("workflows-data", VOLUME) },
    healthcheck: "/ping",
    healthcheckTimeout: 300,
    deploy: { restartPolicyType: "ALWAYS" },
  });

  const dashboard = service("dashboard", {
    source: fromRepo("dashboard"),
    env: {
      // Railway injects PORT=8080 unless a PORT variable exists, and the Next
      // apps must listen on 3000 (server-side tRPC calls localhost:3000).
      PORT: "3000",
      AUTH_SECRET: AUTH_SECRET,
      NEXT_PUBLIC_URL: "https://${{RAILWAY_PUBLIC_DOMAIN}}",
      RESEND_API_KEY: "re_placeholder_not_configured",
      DATABASE_URL: libsql.env.DATABASE_URL,
      CRON_SECRET: workflows.env.CRON_SECRET,
      TINY_BIRD_API_KEY: tinybird.env.TB_LOCAL_WORKSPACE_TOKEN,
      TINYBIRD_URL: tinybird.env.TINYBIRD_URL,
    },
    healthcheck: "/login",
    healthcheckTimeout: 300,
    deploy: { restartPolicyType: "ALWAYS" },
  });

  const statusPage = service("status-page", {
    source: fromRepo("status-page"),
    env: {
      PORT: dashboard.env.PORT,
      AUTH_SECRET: dashboard.env.AUTH_SECRET,
      DATABASE_URL: libsql.env.DATABASE_URL,
      CRON_SECRET: workflows.env.CRON_SECRET,
      RESEND_API_KEY: dashboard.env.RESEND_API_KEY,
      TINY_BIRD_API_KEY: tinybird.env.TB_LOCAL_WORKSPACE_TOKEN,
      TINYBIRD_URL: tinybird.env.TINYBIRD_URL,
    },
    healthcheck: "/robots.txt",
    healthcheckTimeout: 300,
    deploy: { restartPolicyType: "ALWAYS" },
  });

  const server = service("server", {
    source: fromRepo("server"),
    env: {
      PORT: dashboard.env.PORT,
      DATABASE_URL: libsql.env.DATABASE_URL,
      CRON_SECRET: workflows.env.CRON_SECRET,
      RESEND_API_KEY: dashboard.env.RESEND_API_KEY,
      TINY_BIRD_API_KEY: tinybird.env.TB_LOCAL_WORKSPACE_TOKEN,
      TINYBIRD_URL: tinybird.env.TINYBIRD_URL,
    },
    healthcheck: "/ping",
    healthcheckTimeout: 300,
    deploy: { restartPolicyType: "ALWAYS" },
  });

  // ---------------------------------------------------------------- Monitoring
  const ingest = service("private-location", {
    source: fromRepo("private-location"),
    env: {
      DB_URL: libsql.env.DATABASE_URL,
      TINYBIRD_TOKEN: tinybird.env.TB_LOCAL_WORKSPACE_TOKEN,
      TINYBIRD_URL: tinybird.env.TINYBIRD_URL,
      WORKFLOWS_URL: workflows.env.WORKFLOWS_URL,
      CRON_SECRET: workflows.env.CRON_SECRET,
      INGEST_URL: "http://${{RAILWAY_PRIVATE_DOMAIN}}:8080",
    },
    healthcheck: "/health",
    healthcheckTimeout: 600,
    deploy: { restartPolicyType: "ALWAYS" },
  });

  const probe = service("probe", {
    source: image("ghcr.io/openstatushq/private-location:latest"),
    env: {
      OPENSTATUS_INGEST_URL: ingest.env.INGEST_URL,
      OPENSTATUS_KEY: PROBE_KEY,
    },
    deploy: { restartPolicyType: "ALWAYS" },
  });

  const cron = service("cron", {
    source: fromRepo("cron"),
    env: {
      CRON_SECRET: workflows.env.CRON_SECRET,
      WORKFLOWS_URL: workflows.env.WORKFLOWS_URL,
      DATABASE_URL: libsql.env.DATABASE_URL,
      TINYBIRD_URL: tinybird.env.TINYBIRD_URL,
      OPENSTATUS_KEY: probe.env.OPENSTATUS_KEY,
    },
    deploy: { restartPolicyType: "ALWAYS" },
  });

  return project("openstatus", {
    resources: [
      group("Data", [libsql, tinybird]),
      group("Jobs", [dbMigrate, tinybirdDeploy]),
      group("Apps", [dashboard, statusPage, server, workflows]),
      group("Monitoring", [ingest, probe, cron]),
    ],
  });
});
