import {
  defineRailway,
  github,
  group,
  image,
  project,
  service,
  volume,
} from "railway/iac";

// The GitHub repo that holds this file plus the three helper images
// (cron sidecar, Tinybird Local wrapper, Tinybird schema loader).
const TEMPLATE_REPO = "ephraimduncan/openstatus-railway";
const openstatusImage = (name: string) =>
  image(`ghcr.io/openstatushq/openstatus-${name}:latest`);

// Secrets for the reference project. In the published template these are
// replaced by ${{secret(32)}} so every deployment gets its own values.
const AUTH_SECRET = "eMvhfqafUwDIwAOfOCjhKOwGoKIaqpQPMifhjTUjrkXqALrL";
const CRON_SECRET = "f4c1c8d0d94e7fb74448526350d0f5064eebfe712e145124";
const PROBE_KEY = "42d02842a1c64d39b82bfc762f6ac524";

// Tinybird Local only accepts tokens in the `tb local generate-tokens` format
// (HS256 with a fixed key), so these cannot be generated by Railway. They are
// only reachable on the private network. See README > "Rotate the Tinybird tokens".
const TINYBIRD_WORKSPACE_TOKEN = "p.eyJ1IjogIjIzZTE0YmFkLWFlYmQtNGVjMi04MTVkLTMyYmI0ZDllNmI0ZCIsICJpZCI6ICJlZjc2NTEwMi0yM2Y1LTQ5OGQtYTMyZS0zMGJkMWRmNzBkNTciLCAiaG9zdCI6IG51bGx9.crYr6k4p1CXjb4bJ3grPMmRDOz4fIoU-fgdJ420bnvo";
const TINYBIRD_USER_TOKEN = "p.eyJ1IjogIjI2OTVhNDEzLTllMTctNDE1YS1hOWFmLTJmMzMxZWMyYzViOCIsICJpZCI6ICIyZDk1YjY1My1hMTA4LTRkZTUtYjc4Mi01ZjE1OTNhZmIwZGUiLCAiaG9zdCI6IG51bGx9.RLsa0HY5A7pP5FnytWFTIwHRIwtacPmKKeaoF6_2L9M";

const describe = (value: string, description: string, isOptional = false) => ({
  value,
  description,
  isOptional,
});

export default defineRailway(() => {
  // ---------------------------------------------------------------- Data
  const libsql = service("libsql", {
    source: image("ghcr.io/tursodatabase/libsql-server:latest"),
    env: {
      SQLD_NODE: "primary",
      SQLD_MAX_CONCURRENT_CONNECTIONS: "512",
      SQLD_MAX_CONCURRENT_REQUESTS: "1024",
      PORT: describe("8080", "libSQL HTTP port (used for the healthcheck)"),
      DATABASE_URL: describe(
        "http://${{RAILWAY_PRIVATE_DOMAIN}}:8080",
        "libSQL HTTP URL on the private network. Every other service references this value.",
      ),
    },
    volumeMounts: { "/var/lib/sqld": volume("libsql-data") },
    healthcheck: "/health",
    healthcheckTimeout: 300,
    deploy: { restartPolicyType: "ALWAYS" },
  });

  const tinybird = service("tinybird-local", {
    source: github(TEMPLATE_REPO, { branch: "main", rootDirectory: "tinybird-local" }),
    build: { builder: "DOCKERFILE" },
    env: {
      PORT: describe("7181", "Tinybird API port (used for the healthcheck)"),
      TB_LOCAL_WORKSPACE_TOKEN: describe(
        TINYBIRD_WORKSPACE_TOKEN,
        "Tinybird Local workspace admin token. Must be a `tb local generate-tokens` token. Shared with the apps as TINY_BIRD_API_KEY / TINYBIRD_TOKEN.",
      ),
      TB_LOCAL_USER_TOKEN: describe(
        TINYBIRD_USER_TOKEN,
        "Tinybird Local user token. Must be a `tb local generate-tokens` token.",
      ),
      TINYBIRD_URL: describe(
        "http://${{RAILWAY_PRIVATE_DOMAIN}}:7181",
        "Tinybird API base URL on the private network. Never expose this service publicly.",
      ),
    },
    volumeMounts: { "/data": volume("tinybird-data") },
    healthcheck: "/v0/health",
    healthcheckTimeout: 900,
    deploy: { restartPolicyType: "ALWAYS" },
  });

  // ---------------------------------------------------------------- Jobs
  const dbMigrate = service("db-migrate", {
    source: openstatusImage("db-migrate"),
    env: {
      DATABASE_URL: libsql.env.DATABASE_URL,
    },
    deploy: { restartPolicyType: "ON_FAILURE", restartPolicyMaxRetries: 10 },
  });

  const tinybirdDeploy = service("tinybird-deploy", {
    source: github(TEMPLATE_REPO, { branch: "main", rootDirectory: "tinybird-deploy" }),
    build: { builder: "DOCKERFILE" },
    env: {
      TB_HOST: tinybird.env.TINYBIRD_URL,
      TB_TOKEN: tinybird.env.TB_LOCAL_WORKSPACE_TOKEN,
    },
    deploy: { restartPolicyType: "ON_FAILURE", restartPolicyMaxRetries: 20 },
  });

  // ---------------------------------------------------------------- Apps
  const workflows = service("workflows", {
    source: openstatusImage("workflows"),
    env: {
      PORT: "3000",
      NODE_ENV: "production",
      SELF_HOST: "true",
      FLY_REGION: "self-hosted",
      DATABASE_URL: libsql.env.DATABASE_URL,
      CRON_SECRET: describe(
        CRON_SECRET,
        "Shared secret for the /cron/* endpoints and for the ingest server to report status changes. Referenced by the other services.",
      ),
      WORKFLOWS_URL: describe(
        "http://${{RAILWAY_PRIVATE_DOMAIN}}:3000",
        "Workflows URL on the private network (used by the ingest server and the cron sidecar).",
      ),
      SITE_URL: "https://${{dashboard.RAILWAY_PUBLIC_DOMAIN}}",
      RESEND_API_KEY: "${{dashboard.RESEND_API_KEY}}",
      UPSTASH_REDIS_REST_URL: "http://localhost:6379",
      UPSTASH_REDIS_REST_TOKEN: "placeholder",
      TINY_BIRD_API_KEY: tinybird.env.TB_LOCAL_WORKSPACE_TOKEN,
      TINYBIRD_URL: tinybird.env.TINYBIRD_URL,
      RAILWAY_RUN_UID: describe("0", "The image runs as uid 1000; run as root so the libSQL replica can write to the volume."),
    },
    volumeMounts: { "/app/data": volume("workflows-data") },
    healthcheck: "/ping",
    healthcheckTimeout: 300,
    deploy: { restartPolicyType: "ALWAYS" },
  });

  const dashboard = service("dashboard", {
    source: openstatusImage("dashboard"),
    env: {
      PORT: describe("3000", "Must stay 3000: the app calls itself on localhost:3000 for server-side tRPC."),
      HOSTNAME: "::",
      NODE_ENV: "production",
      SELF_HOST: "true",
      FLY_REGION: "self-hosted",
      AUTH_TRUST_HOST: "true",
      AUTH_SECRET: describe(AUTH_SECRET, "Auth.js secret (at least 32 characters)."),
      NEXT_PUBLIC_URL: "https://${{RAILWAY_PUBLIC_DOMAIN}}",
      DATABASE_URL: libsql.env.DATABASE_URL,
      CRON_SECRET: workflows.env.CRON_SECRET,
      RESEND_API_KEY: describe(
        "re_placeholder_not_configured",
        "Optional. Login works without it: the magic link is printed in this service's logs. Set a real Resend key to send notification emails.",
      ),
      UPSTASH_REDIS_REST_URL: "http://localhost:6379",
      UPSTASH_REDIS_REST_TOKEN: "placeholder",
      TINY_BIRD_API_KEY: tinybird.env.TB_LOCAL_WORKSPACE_TOKEN,
      TINYBIRD_URL: tinybird.env.TINYBIRD_URL,
    },
    healthcheck: "/login",
    healthcheckTimeout: 300,
    deploy: { restartPolicyType: "ALWAYS" },
  });

  const statusPage = service("status-page", {
    source: openstatusImage("status-page"),
    env: {
      PORT: describe("3000", "Must stay 3000: the app calls itself on localhost:3000 for server-side tRPC."),
      HOSTNAME: "::",
      NODE_ENV: "production",
      SELF_HOST: "true",
      FLY_REGION: "self-hosted",
      AUTH_TRUST_HOST: "true",
      AUTH_SECRET: dashboard.env.AUTH_SECRET,
      DATABASE_URL: libsql.env.DATABASE_URL,
      CRON_SECRET: workflows.env.CRON_SECRET,
      RESEND_API_KEY: dashboard.env.RESEND_API_KEY,
      UPSTASH_REDIS_REST_URL: "http://localhost:6379",
      UPSTASH_REDIS_REST_TOKEN: "placeholder",
      TINY_BIRD_API_KEY: tinybird.env.TB_LOCAL_WORKSPACE_TOKEN,
      TINYBIRD_URL: tinybird.env.TINYBIRD_URL,
    },
    healthcheck: "/robots.txt",
    healthcheckTimeout: 300,
    deploy: { restartPolicyType: "ALWAYS" },
  });

  const server = service("server", {
    source: openstatusImage("server"),
    env: {
      PORT: "3000",
      NODE_ENV: "production",
      SELF_HOST: "true",
      FLY_REGION: "self-hosted",
      DATABASE_URL: libsql.env.DATABASE_URL,
      CRON_SECRET: workflows.env.CRON_SECRET,
      RESEND_API_KEY: dashboard.env.RESEND_API_KEY,
      UPSTASH_REDIS_REST_URL: "http://localhost:6379",
      UPSTASH_REDIS_REST_TOKEN: "placeholder",
      TINY_BIRD_API_KEY: tinybird.env.TB_LOCAL_WORKSPACE_TOKEN,
      TINYBIRD_URL: tinybird.env.TINYBIRD_URL,
    },
    healthcheck: "/ping",
    healthcheckTimeout: 300,
    deploy: { restartPolicyType: "ALWAYS" },
  });

  // ---------------------------------------------------------------- Monitoring
  const ingest = service("private-location", {
    source: openstatusImage("private-location"),
    env: {
      PORT: "8080",
      GIN_MODE: "release",
      DB_URL: libsql.env.DATABASE_URL,
      TINYBIRD_TOKEN: tinybird.env.TB_LOCAL_WORKSPACE_TOKEN,
      TINYBIRD_URL: tinybird.env.TINYBIRD_URL,
      WORKFLOWS_URL: workflows.env.WORKFLOWS_URL,
      CRON_SECRET: workflows.env.CRON_SECRET,
      INGEST_URL: describe(
        "http://${{RAILWAY_PRIVATE_DOMAIN}}:8080",
        "Ingest server URL on the private network (the probe reports here).",
      ),
    },
    healthcheck: "/health",
    healthcheckTimeout: 600,
    deploy: { restartPolicyType: "ALWAYS" },
  });

  const probe = service("probe", {
    source: image("ghcr.io/openstatushq/private-location:latest"),
    env: {
      OPENSTATUS_INGEST_URL: ingest.env.INGEST_URL,
      OPENSTATUS_KEY: describe(
        PROBE_KEY,
        "Private location token. After first login run `os-admin register-probe <workspace-id>` on the cron service, or paste the token of a private location created in the dashboard.",
      ),
    },
    deploy: { restartPolicyType: "ALWAYS" },
  });

  const cron = service("cron", {
    source: github(TEMPLATE_REPO, { branch: "main", rootDirectory: "cron" }),
    build: { builder: "DOCKERFILE" },
    env: {
      CRON_SECRET: workflows.env.CRON_SECRET,
      WORKFLOWS_URL: workflows.env.WORKFLOWS_URL,
      DATABASE_URL: libsql.env.DATABASE_URL,
      TINYBIRD_URL: tinybird.env.TINYBIRD_URL,
      OPENSTATUS_KEY: probe.env.OPENSTATUS_KEY,
    },
    deploy: { restartPolicyType: "ALWAYS" },
  });

  return project("openstatus", {
    resources: [
      group("Data", [libsql, tinybird]),
      group("Jobs", [dbMigrate, tinybirdDeploy]),
      group("Apps", [dashboard, statusPage, server, workflows]),
      group("Monitoring", [ingest, probe, cron]),
    ],
  });
});
